#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "RRxy4/orZzJP"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 2

#define RGB_MATRIX_STARTUP_SPD 60

